### ISSUE TITLE
Consider backends from gnome-dictionary

### ISSUE THREAD

**Issue by janxkoci** [lainsce/palaura#43] opened 2020-02-06 16:06 UTC
Hi,

I noticed in your changelog for the recent update that you were looking for a free backend/API, but haven't found any, so you continue to use some paid API (I guess) and try to pay for it by selling the app.

> Release: Hot Revival
> Update: In the lack of a better API that is free of charge, I decided to continue using the one in-app. As such, the new pricing will help accomodate the costs.

I have nothing against selling your app, it's great and deserves all the money it needs.

But have you considered the backends used in `gnome-dictionary`? There is **a lot** of them, maybe you can use some for free.

**Comment by lainsce** [comment] 2020-02-06 21:46
The problem is that to do that, I would need to rewrite the whole backend to fit gnome-dictionary's, and even hard depend on the app if there's no common library. I would _LOVE_ if someone helped me with this.

**Comment by janxkoci** [comment] 2020-02-07 11:04
I'm not a programmer (aside from some science scripting), but it seems [gnome-dictionary](https://gitlab.gnome.org/GNOME/gnome-dictionary) is just using some standard protocol, [called dict](https://tools.ietf.org/html/rfc2229) to fetch results from online dictionaries. Maybe it doesn't need full rewrite, just support for the protocol..

**Comment by lainsce** [comment] 2020-02-07 14:53
I'll see what I can do.

**Comment by janxkoci** [comment] 2020-03-05 10:14
I was thinking about this little more and I no longer think it's such a good idea. It's because most of the time **Palaura has superior results** when compared to gnome-dictionary. Not to mention that it _just works_, while gnome-dictionary requires some playing around and switching dictionaries on and off, precisely because it has so many of them. There is always some tradeoff with it.

May I ask which backend are you actually using?

**Comment by janxkoci** [comment] 2020-03-05 10:26
In case you decide to work on it, I can offer some recommendations.

- In my experience **WordNet** has the most useful results, so I would start there, maybe as a fallback. But it doesn't contain as many words, so every now and then I have to switch on other dictionaries (luckily gnome-dictionary offers also "all english dicts" and similar groupings) to check the query.
- Often **Webster** has some results after WordNet failed, but their results are quite cryptic, using very old-fashioned English and weird examples (the sort of examples where I have to look up every other word). FYI The 1903 Webster dictionary is called "The Collaborative International Dictionary of English v.0.48" in the dict-selector UI of gnome-dictionary.
  - Still, Palaura has even more words, and with more legible definitions & examples.
- Moby Thesaurus can be useful too.

I don't think you need to consider other dictionary sources, I rarely even see results from them.

**Comment by lainsce** [comment] 2020-03-05 13:17
The problem with adding other sources is that I'd need to rewrite the whole backend and completely rework all of the GUI, which would mean Palaura would be needlessly complex.
Since you think it's not needed and the current API is great, I'll close this.

**Closed by lainsce** 2020-03-05 13:17 UTC
Labels: enhancement
